import { app, dialog, type BrowserWindow, type MessageBoxOptions } from 'electron'
import { createRequire } from 'node:module'
import { log } from './logging.js'

const require = createRequire(import.meta.url)
const { autoUpdater } = require('electron-updater') as typeof import('electron-updater')

/**
 * Update support against GitHub Releases (feed generated by electron-builder).
 * Downloads and restarts only with explicit user consent.
 *
 * The check is manual by default (Help → Check for updates) so the app stays
 * offline unless the user asks; set MOSAIC_AUTO_UPDATE=1 to check on startup.
 * Private repos need a published (non-draft) release to be visible.
 */
export function setupAutoUpdates(getWindow: () => BrowserWindow | null): void {
  if (!app.isPackaged) {
    log.info('Auto-update disabled outside a packaged build')
    return
  }
  // electron-log implements the logger interface at runtime.
  autoUpdater.logger = log as unknown as typeof autoUpdater.logger
  autoUpdater.autoDownload = false
  autoUpdater.allowDowngrade = false

  autoUpdater.on('error', (error) => log.error('Auto-update error', error))
  autoUpdater.on('update-not-available', () => log.info('No updates available'))

  autoUpdater.on('update-available', (info) => {
    void prompt(getWindow, {
      type: 'info',
      title: 'Update available',
      message: `Mosaic ${info.version} is available.`,
      detail: 'Download it now? The app will ask to restart when it is ready.',
      buttons: ['Download', 'Later'],
      defaultId: 0,
      cancelId: 1,
    }).then((choice) => {
      if (choice === 0) void autoUpdater.downloadUpdate().catch((error) => log.error('Update download failed', error))
    })
  })

  autoUpdater.on('update-downloaded', (info) => {
    void prompt(getWindow, {
      type: 'info',
      title: 'Update ready',
      message: `Mosaic ${info.version} has been downloaded.`,
      detail: 'Restart now to finish installing it?',
      buttons: ['Restart', 'Later'],
      defaultId: 0,
      cancelId: 1,
    }).then((choice) => {
      if (choice === 0) autoUpdater.quitAndInstall()
    })
  })

  if (process.env['MOSAIC_AUTO_UPDATE'] === '1') void checkForUpdates()
}

export function checkForUpdates(): Promise<void> {
  if (!app.isPackaged) {
    log.info('Update check skipped outside a packaged build')
    return Promise.resolve()
  }
  return autoUpdater.checkForUpdates().then(() => undefined).catch((error: unknown) => {
    log.warn('Update check failed', error)
  })
}

async function prompt(
  getWindow: () => BrowserWindow | null,
  options: MessageBoxOptions,
): Promise<number> {
  const owner = getWindow()
  const result = owner ? await dialog.showMessageBox(owner, options) : await dialog.showMessageBox(options)
  return result.response
}
